### ISSUE TITLE
Support for Show Whitespace plugin

### ISSUE THREAD

**Issue by onetrev** [ostranme/flat-attack-dark#1]
Nice new theme! Just wondering if there was any chance you could add support for https://github.com/DennisKehrig/brackets-show-whitespace ?

By default the spaces (dots) and tabs (dashes) are heavy / too bright I think.

No worries either way. Cheers and thanks!

**Comment by ostranme** [comment]
Hey! yea certainly....thanks for opening an issue...this was my 1st attempt at a brackets theme so I can definitely look into supporting the above issue. I will look into having it done over the weekend and let you know how everything goes...thanks for the support and glad you like the theme!

**Comment by ostranme** [comment]
I went ahead and tried to change the color to match the light gray of the comments. Looks like the brackets-show-whitespace extension will default to white (#000) if you do not specify. Let me know if the update to the lighter gray works....if not I can try a few other lighter colors or please feel free to suggest different one. 

You should have an update (1.0.1) for the flat-attack-dark theme with a light gray color for white spaces.

**Comment by onetrev** [comment]
Awesome! Thanks for doing that so fast. I think it still needs to be more subtle as those dots and dashes stand out way too much still (in my opinion) ;) 

Something closer to maybe how it was done in this theme? https://github.com/nickfmc/flatlandish

**Comment by ostranme** [comment]
No worries I see what you are talking about now. Thanks for showing me an example. I just updated the theme again with a more subtle gray and looks a lot better! Let me know if I can provide any more support. I'll look into other popular extensions like the whitespace. Feel free to open more issues if you see anything wrong or what more.

**Comment by onetrev** [comment]
Perfect! Agreed, that's much better. Thank you very much. I think you can safely close this issue now. Cheers!
