### ISSUE TITLE
Tag highlight transparency

### ISSUE THREAD

**Issue by onetrev** [ostranme/flat-attack-dark#2]
Active tag highlighting (when your cursor is within an HTML tag for example) is a solid colour. As such you can no longer see the colouring of the items within the tag, like class / id colour, or class name colour, etc. 

It's also a bit bright being white right now, in my opinion. I've noticed a lot of themes add transparency to the highlighting so you can still see what's going on within the tag your cursor is on. Some have underline too. Not sure you need both, but just throwing that out there.

**Comment by ostranme** [comment]
Will work on making it easier to read. I agree that the white is harsh. Do you have a preference on transparent color vs underline?

**Comment by onetrev** [comment]
I think transparency is better than underline. And definitely no need to do both.

**Comment by ostranme** [comment]
keeping issue open as a reminder until I fix it

**Comment by ostranme** [comment]
Updated to transparent blue/green for tags and brackets/braces. The brackets/braces may need a different background color to be able to identify the closing. Let me know what you think.

**Comment by onetrev** [comment]
Hmm, it doesn't seem to be transparent? Or wait, maybe it is, but the problem is the text within the tag is all turning white. I think it's much more useful is you can still see the code colouring of the text within the tag.

**Comment by ostranme** [comment]
Gotcha yea the blue is at a .5 opacity with white text right now. I'll look into finding a readable background color while keeping the class and tag colors.

**Comment by ostranme** [comment]
Is the gray too light? Not sure if you would want to highlight the matching tag more vibrant so you can find it or be subtle about it.

![screen shot 2015-04-22 at 2 52 12 pm](https://cloud.githubusercontent.com/assets/5865367/7282625/33f27cd4-e8ff-11e4-8200-5a361333e935.png)

**Comment by ostranme** [comment]
Is the gray too light? Not sure if you would want to highlight the matching tag more vibrant so you can find it or be subtle about it.

Open to suggestions....darker...lighter.....vibrant color to stand out more.

![screen shot 2015-04-22 at 2 52 12 pm](https://cloud.githubusercontent.com/assets/5865367/7282676/8ba13146-e8ff-11e4-9dad-f9118a3274e2.png)

**Comment by ostranme** [comment]
Is the gray too light? Not sure if you would want to highlight the matching tag more vibrant so you can find it or be subtle about it.

Open to suggestions....darker...lighter.....vibrant color to stand out more.

![screen shot 2015-04-22 at 2 54 48 pm](https://cloud.githubusercontent.com/assets/5865367/7282697/b4127cfc-e8ff-11e4-9fe6-f18eb65766d9.png)

![screen shot 2015-04-22 at 2 52 12 pm](https://cloud.githubusercontent.com/assets/5865367/7282698/b68705f2-e8ff-11e4-872a-140ec04cb34a.png)

**Comment by onetrev** [comment]
No I think that's perfect. Thanks!!

**Comment by ostranme** [comment]
Theme has been updated. Going to close issue. Thanks!
